### ISSUE TITLE
Content-type not set correctly on a collection export

### ISSUE THREAD

**Issue by SirVaidas** [apideck-libraries/postman-to-k6#132]
Hey, 

When exporting collection and when body of it has content type set to application/json in Postman, this is not persisted in the converted collection

![image](https://github.com/apideck-libraries/postman-to-k6/assets/161447704/0ac7c78f-8482-43c1-bf99-8c8afbabfa8f)
![image](https://github.com/apideck-libraries/postman-to-k6/assets/161447704/5026e4ed-39b9-43f7-a6dd-4a67c6df7b98)

If I add headers to the exported request manually it works as expected
![image](https://github.com/apideck-libraries/postman-to-k6/assets/161447704/ce7435a0-7a87-4cd8-bf5b-b607f2f7d7a0)

Is there a way to either pass the headers from Postman to k6 via the `postman-to-k6` or convert the value of 
`item.request.body.options.raw.language` to a proper content-type header?

**Comment by SirVaidas** [comment]
Seems, that it works as expected if you manually specify Content-Type for each of the requests in postman.
![image](https://github.com/apideck-libraries/postman-to-k6/assets/161447704/89a22d89-8113-485a-bf27-56a880da5e3e)

**Comment by thim81** [comment]
hi @SirVaidas 

We have some work-arounds documented for this Postman specific side-effect:
https://github.com/apideck-libraries/postman-to-k6/discussions/42#discussioncomment-2271512

Possible solutions:

- Set the desired header explicitly in Postman, so that it is part of the Postman collection when exported
- Manually add the [K6 params options](https://k6.io/docs/javascript-api/k6-http/params/)
- Pass it postman-to-k6 using the [--k6-params](https://github.com/apideck-libraries/postman-to-k6#k6-param-options-file)

In the [discussion](https://github.com/apideck-libraries/postman-to-k6/discussions/42#discussioncomment-2271512), you find more details

**Comment by SirVaidas** [comment]
Hey @thim81,

Perfect, thank you very much for the follow up!
